# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f502b0bff1fcce8ff0cf2587f769d143c91023fd9ecf9ac026979712cacec3fefb5580edd847e4ce816fc0ffa6ae61c76dc1726a9b5959a416731590ed8444d

test:
  secret_key_base: 1a73db4950405d70751f911ee2ebf41c016518cf371189885c6d2b2b91ca5b1cfea590699e3bab6aedcfffb5abb084a60236cdaf1df580ae290d7919459c7aca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
